/*
 * This source file was generated by the Gradle 'init' task
 */
package com.hogemann.bsky2rss;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer;
import com.hogemann.bsky2rss.bsky.BlueSkyService;
import okhttp3.OkHttpClient;

import java.time.Instant;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        final ObjectMapper mapper = new ObjectMapper();
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        final JavaTimeModule javaTimeModule = new JavaTimeModule();
        javaTimeModule.addDeserializer(Instant.class, InstantDeserializer.INSTANT);
        mapper.registerModule(javaTimeModule);

        // Read from environment variables
        final String identity = System.getenv("BSKY_IDENTITY");
        final String password = System.getenv("BSKY_PASSWORD");

        BlueSkyService service = new BlueSkyService(
                "https://bsky.social/xrpc",
                new OkHttpClient(),
                mapper
        );
        service.login(identity, password)
                .flatMap(auth -> service.createPostWithLinkCard(
                        auth.accessJwt(),
                        auth.did(),
                        "Wonder how my code handles YouTube card embeds...",
                        "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                ))
                .ifOkOrElse(
                        result -> System.out.println("Ok: " + result),
                        error -> System.err.println("Error: " + error)
                );
    }
}
